apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: wildcard-hostiflix-com
  namespace: kube-system
spec:
  secretName: wildcard-hostiflix-com
  issuerRef:
    name: letsencrypt-prod-dns
    kind: ClusterIssuer
  dnsNames:
    - '*.hostiflix.com'
  acme:
    config:
      - dns01:
          provider: cf-dns
        domains:
          - '*.hostiflix.com'