apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging-dns
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: hostiflix@remllov.de
    privateKeySecretRef:
      name: letsencrypt-staging-dns
    dns01:
      providers:
        - name: cf-dns
          cloudflare:
            email: hostiflix@remllov.de
            apiKeySecretRef:
              name: cloudflare-api-key
              key: api-key.txt